export function buildBannerPrompt(student, refCounts = {}, copy = null) {
  const styleRefs = refCounts.styleRefs ?? 0;
  const logos = refCounts.logos ?? 0;
  // Copy may be passed in (preferred — generated by lib/copywriter.js via Claude),
  // or fall back to the deterministic template if absent (e.g. local debugging).
  const finalCopy = copy ?? buildCopy(student);
  const wordsLine = Array.isArray(student.three_words) && student.three_words.length
    ? student.three_words.join(", ")
    : "—";

  return `Design ONE 1200×628 horizontal marketing banner for IE Business School,
featuring a real student as the hero. Output a single PNG image only.

ABSOLUTE REQUIREMENTS (do not violate):

1. FACE PRESERVATION — reference image #1 is the student's actual portrait.
   Reproduce their face exactly: eye shape and color, nose, mouth, hair color
   and style, skin tone, facial proportions, age. Do NOT generate a different
   person, a stylized version, an AI-generated face, a celebrity, or a
   composite. The student in the banner must be unmistakably the same person
   as in image #1.

2. RENDER ALL FOUR COPY ELEMENTS BELOW, each as crisp legible typography,
   spelled letter-for-letter as shown — no garbled letters, no misspellings,
   no extra characters, no duplicated words. Hierarchy from largest to
   smallest: header > subheader > body > CTA.

      HEADER (largest, boldest, hero text):
        "${finalCopy.header}"

      SUBHEADER (medium, just under the header):
        "${finalCopy.subheader}"

      BODY (small paragraph, max two short lines):
        "${finalCopy.body}"

      CALL TO ACTION (rendered as a button-style label — pill shape or solid
      rectangle, high contrast against the background):
        "${finalCopy.cta}"

   If you cannot render any of these strings with flawless typography, retry
   the composition rather than producing distorted letters.

3. LOGO IS MANDATORY — the IE logo (last reference image(s)) must appear in
   the final banner, placed in a top corner with adequate clear space, in its
   official colors, undistorted, perfectly legible. A banner without the IE
   logo is unacceptable.

REFERENCE IMAGES IN ORDER
#1  Student portrait — the hero. Use ONLY this face. See requirement 1.
${
  styleRefs > 0
    ? `#2–${1 + styleRefs}  IE banner samples — match this visual language: color palette,
    typography style, layout balance, photographic treatment. Do not copy
    layouts 1:1; compose freshly around the new copy.`
    : "(no banner style references provided)"
}
${
  logos > 0
    ? `#${styleRefs + 2}–${styleRefs + 1 + logos}  IE logos — place verbatim in a top corner with adequate clear
    space. Do not redraw, recolor, distort, crop, or stylize the logo.`
    : "(no logo references provided)"
}

STUDENT CONTEXT (informs mood and composition, NOT what's drawn literally)
- Name: ${student.full_name ?? "—"}
- Country: ${student.country ?? "—"}${student.city ? `, ${student.city}` : ""}
- Career goal: ${student.career_goal_one_line ?? "—"}
- Dream company / industry: ${student.dream_company_or_industry ?? "—"}
- Target program: ${student.top_program_interest ?? "—"}
- Self-described in three words: ${wordsLine}
- Visual vibe: ${student.visual_vibe ?? "Bold"}
- Tone: ${student.tone_preference ?? "Inspirational"}

COMPOSITION
- Aspect ratio: 1200×628 (wide horizontal banner).
- Two-zone layout: hero subject (the student) on one side taking ~40–55% of
  the frame; copy stack (header → subheader → body → CTA) on the opposite
  side, top-to-bottom, generously spaced.
- IE logo: top corner of the copy side.
- High contrast between text and background; readable on social feeds.
- Photographic, premium, contemporary. NOT a flat illustration, NOT
  cartoonized, NOT a stock-photo aesthetic, NOT a generic gradient.

OUTPUT: exactly one 1200×628 PNG banner. No alternative versions, no collage.`;
}

// Build all four copy elements deterministically from student fields. The
// model receives these verbatim, so any tweak here propagates to every
// banner without re-prompting.
function buildCopy(student) {
  const tone = (student.tone_preference ?? "Inspirational").toLowerCase();
  const firstName = (student.full_name ?? "").split(/\s+/)[0] || "You";
  const goal = clean(student.career_goal_one_line);
  const dream = clean(student.dream_company_or_industry);
  const program = humanizeProgram(student.top_program_interest);
  const country = clean(student.country);
  const words = Array.isArray(student.three_words) ? student.three_words.filter(Boolean) : [];

  const header = pickHeader({ tone, goal, dream, firstName });
  const subheader = program
    ? `${program} · IE Business School`
    : "Your path. Your program. IE Business School.";
  const body = pickBody({ tone, firstName, goal, dream, country, words });
  const cta = pickCta({ tone, program });

  return {
    header: truncate(header, 60),
    subheader: truncate(subheader, 70),
    body: truncate(body, 180),
    cta: truncate(cta, 26),
  };
}

function pickHeader({ tone, goal, dream, firstName }) {
  if (goal) {
    const cleaned = goal.replace(/[.!?]+$/, "");
    return truncateWords(capitalize(cleaned), 8);
  }
  if (dream) {
    return truncateWords(`Built for ${dream}.`, 6);
  }
  if (tone === "witty") return `Skip the lottery, ${firstName}.`;
  if (tone === "professional") return "Your next career chapter.";
  if (tone === "conversational") return "Ready when you are.";
  return "Your future, designed.";
}

function pickBody({ tone, firstName, goal, dream, country, words }) {
  const traitClause = words.length
    ? ` Built for ${joinWithAnd(words.slice(0, 3))} minds.`
    : "";
  const targetClause = dream ? ` Aim: ${dream}.` : "";
  const placeClause = country ? ` From ${country} to the world.` : "";

  if (tone === "witty") {
    return `${firstName}, the boring version of your résumé starts today.${traitClause}${targetClause}`.trim();
  }
  if (tone === "professional") {
    return `A career-ready master designed around your ambition.${targetClause}${traitClause}`.trim();
  }
  if (tone === "conversational") {
    return `Hey ${firstName} — let's build a path that fits you.${placeClause}${traitClause}`.trim();
  }
  // Inspirational (default)
  return `${firstName}, this is where ambition meets craft.${placeClause}${traitClause}${targetClause}`.trim();
}

function pickCta({ tone, program }) {
  if (program && tone !== "witty") return `Explore the ${truncateWords(program, 4)} →`;
  if (tone === "witty") return "Apply (boldly) →";
  if (tone === "professional") return "Start your application →";
  if (tone === "conversational") return "Let's talk →";
  return "Apply now →";
}

function humanizeProgram(slug) {
  if (!slug) return null;
  // Slugs from knowledge_base/programs.jsonl look like "master-in-big-data-business-analytics"
  return slug
    .replace(/-/g, " ")
    .replace(/\b(\w)/g, (c) => c.toUpperCase())
    .replace(/\bMba\b/gi, "MBA")
    .replace(/\bIe\b/gi, "IE")
    .replace(/\bIn\b/g, "in")
    .replace(/\bOf\b/g, "of")
    .replace(/\bAnd\b/g, "and")
    .replace(/^Master in/, "Master in");
}

function clean(v) {
  return typeof v === "string" ? v.trim() : "";
}
function capitalize(s) {
  return s ? s[0].toUpperCase() + s.slice(1) : s;
}
function truncateWords(s, n) {
  const parts = s.split(/\s+/);
  return parts.length <= n ? s : parts.slice(0, n).join(" ");
}
function truncate(s, n) {
  return s.length <= n ? s : s.slice(0, n - 1).trim() + "…";
}
function joinWithAnd(arr) {
  if (arr.length <= 1) return arr.join("");
  if (arr.length === 2) return `${arr[0]} and ${arr[1]}`;
  return `${arr.slice(0, -1).join(", ")} and ${arr[arr.length - 1]}`;
}
